namespace QuizAPI.Services.Audit
{
    /// <summary>
    /// Canonical audit action verbs. Always reference these constants instead of raw
    /// strings — the audit query filters by exact Action text, so a typo silently
    /// breaks searching. Convention: "EntityPastTenseVerb" in PascalCase.
    /// </summary>
    public static class AuditActions
    {
        // Authentication / account
        public const string UserLoggedIn = "UserLoggedIn";
        public const string LoginFailed = "LoginFailed";
        public const string UserSignedUp = "UserSignedUp";
        public const string UserEmailConfirmed = "UserEmailConfirmed";
        public const string UserCreated = "UserCreated";
        public const string UserDeleted = "UserDeleted";
        // A user's role set was changed by an admin (from the Users page).
        public const string UserRolesChanged = "UserRolesChanged";

        // External sign-in (Google/Microsoft — see docs/auth/social-login-plan.md).
        // Logged when a provider identity is linked to a user, at auto-link or external signup.
        public const string ExternalAccountLinked = "ExternalAccountLinked";

        // Invite codes (signup gate — see docs/auth/invite-code-system-plan.md)
        public const string InviteCodeRedeemed = "InviteCodeRedeemed";
        public const string InviteCodesGenerated = "InviteCodesGenerated";
        public const string InviteCodeRevoked = "InviteCodeRevoked";

        // Questions
        public const string QuestionCreated = "QuestionCreated";
        public const string QuestionUpdated = "QuestionUpdated";
        public const string QuestionDeleted = "QuestionDeleted";

        // Quizzes
        public const string QuizCreated = "QuizCreated";

        /// <summary>
        /// Questions were generated by the hosted model. Logged on generation, not on save — a
        /// user may generate and then abandon, and the provenance of a quiz is reconstructed by
        /// pairing this with the QuizCreated entry that follows it.
        /// </summary>
        public const string AiQuizGenerated = "AiQuizGenerated";
        public const string QuizUpdated = "QuizUpdated";
        public const string QuizDeleted = "QuizDeleted";

        // Roles (definitions). Per-user role grants are captured by UserCreated.
        public const string RoleCreated = "RoleCreated";
        public const string RoleUpdated = "RoleUpdated";
        public const string RoleDeleted = "RoleDeleted";

        // Permissions (role ↔ permission assignments, edited from the Permissions page).
        public const string RolePermissionGranted = "RolePermissionGranted";
        public const string RolePermissionRevoked = "RolePermissionRevoked";
    }
}
